//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniPuan.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class UP_ST_UNIVERSITY
    {
        public int UNIVERSITYID { get; set; }
         [DisplayName("Üniversiteler")]
        public string UNIVERSITYNAME { get; set; }
        public int CITYID { get; set; }
        public int UNITYPEID { get; set; }
    }
}
