//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniPuan.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UP_ST_CITY
    {
        public UP_ST_CITY()
        {
            this.UP_ST_DEPARTMENT = new HashSet<UP_ST_DEPARTMENT>();
        }
    
        public int CITYID { get; set; }
        public string CITYNAME { get; set; }
    
        public virtual ICollection<UP_ST_DEPARTMENT> UP_ST_DEPARTMENT { get; set; }
    }
}
