//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniPuan.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UP_ST_DEPARTMENT
    {
        public int DEPARTMENTID { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string SCORETYPE { get; set; }
        public string EDUTYPE { get; set; }
    }
}
