//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniPuan.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UP_ST_PROGRAM
    {
        public double PROGRAMID { get; set; }
        public string UNIVERSITYNAME { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public Nullable<int> QUOTAS { get; set; }
        public string CONDITION { get; set; }
        public string SCORETYPE { get; set; }
        public Nullable<double> SCOREMIN { get; set; }
        public Nullable<double> ORDERR { get; set; }
        public Nullable<int> DEPARTMENTID { get; set; }
        public Nullable<int> UNIVERSITYID { get; set; }
    
        public virtual UP_ST_PROGRAM UP_ST_PROGRAM1 { get; set; }
        public virtual UP_ST_PROGRAM UP_ST_PROGRAM2 { get; set; }
    }
}
